# Use custom format
format = """
[╭─](surface2)$os$username$hostname$directory$git_branch$battery
[╰─](surface2)$character """

palette = "catppuccin_mocha"
# add_newline = false

[character] 
success_symbol = "[❯](peach)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "bold flamingo"
format = "[$user]($style) "
disabled = false

# Hostname settings
[hostname]
ssh_only = false
format =  "[on](text) [$hostname](bold maroon) "
trim_at = ".companyname.com"
disabled = false
ssh_symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 4
truncation_symbol = "…/"
style = "bold blue"
format = "[in](text) [$read_only]($read_only_style)[$path]($style) "
disabled = false

# cmd_duration config
[cmd_duration]
show_milliseconds = true
style = "bold yellow"
format = "took [$duration]($style)"

[git_branch]
symbol = " "
style = "bold mauve"
format = '[at](text) [$symbol$branch]($style)'
truncation_length = 17
truncation_symbol = ""

[os]
format = '[$symbol](bold overlay1)'   
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
format = "[$symbol$percentage]($style)"
style = "yellow bold"
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
